In [16]:
import scipy.io as sio
from scipy.misc import imread
from preprocess.normalize import preprocess_signature
import tf_signet
from tf_cnn_model import TF_CNNModel
import tensorflow as tf
import numpy as np
import pandas as pd
import sys
import os
import scipy.io
from find_largest_image import find_largest
import tqdm 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from xgboost import XGBClassifier
import random
from numpy.random import choice
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

In [2]:
data_folder = 'C:\\Users\\Mert\\Documents\\GitHub\\sigver_bmg\\data\\downloaded_pp_features\\gpds_signet\\exploitation'

In [3]:
data_f=pd.read_csv(os.path.join(data_folder,'data_features.csv'))
visual_f=pd.read_csv(os.path.join(data_folder,'visual_features.csv'))

In [4]:
data_f.head()

   user_id  sig_id  fakeness
0      100       1      True
1      100       2      True
2      100       3      True
3      100       4      True
4      100       5      True

In [5]:
visual_f.head()

,0,1,2,3,4,5,6,7,8,9,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,0.000000,0.515184,0.0,0.446658,0.000000,1.533631,0.000000,0.830734,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.557626,2.271116,0.000000,0.000000,0.0
1,0.775465,0.491479,0.0,0.000000,0.000000,1.406079,0.000000,0.492579,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,1.852994,0.000000,0.114499,0.0
2,0.000000,0.000000,0.0,0.536446,0.000000,1.768807,0.000000,0.676527,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.000000,2.392846,0.000000,0.226075,0.0
3,0.558339,0.000000,0.0,0.693711,0.166456,0.771811,0.643744,0.890198,1.242508,0.0,...,0.0,0.036022,0.000000,0.0,0.0,0.000000,1.391226,0.653054,0.000000,0.0
4,0.000000,0.000000,0.0,0.000000,0.000000,0.227453,1.312067,1.143076,1.002350,0.0,...,0.0,0.000000,0.067551,0.0,0.0,0.000000,0.892711,0.037287,0.196272,0.0

In [6]:
data_f_gen = data_f.loc[data_f['fakeness']==False]
data_f_fake = data_f.loc[data_f['fakeness']==True]
data_f_gen_12 = data_f_gen.loc[data_f_gen['sig_id'].isin(np.arange(1,13))]
data_f_gen_valid_12 = data_f_gen.loc[data_f_gen['sig_id'].isin(np.arange(13,25))]

In [ ]:
scores_sum = 0
run_count = 0
for user_id in tqdm.tqdm(data_f['user_id'].unique(), ascii=True):
    y_train = data_f_gen_12['user_id']==user_id
    X_train = visual_f.loc[y_train.index]
    class_weight = (data_f_gen_12.shape[0]-data_f_gen_12[y_train].shape[0])/data_f_gen_12[y_train].shape[0]
    clf = XGBClassifier(tree_method='gpu_hist',scale_pos_weight=class_weight, objective='multi:softmax', num_class=2)
    # clf = SVC(class_weight='balanced', gamma='scale')
    # clf = MLPClassifier()
    clf.fit(X_train, y_train)
    y_valid_fakes = data_f_fake.loc[data_f_fake['user_id']==user_id]
    y_valid = len(y_valid_fakes.index)*[False]
    X_valid = visual_f.loc[y_valid_fakes.index]
    score = clf.score(X_valid,y_valid)
    # print(score)
    scores_sum += score
    run_count += 1
    y_valid_gens = data_f_gen_valid_12.loc[data_f_gen_valid_12['user_id']==user_id]
    y_valid = len(y_valid_gens.index)*[True]
    X_valid = visual_f.loc[y_valid_gens.index]
    score = clf.score(X_valid,y_valid)
    # print(score)
    scores_sum += score
    run_count += 1
    y_valid_rand_fakes = data_f_gen_valid_12.loc[choice(data_f_gen_valid_12.loc[data_f_gen_valid_12['user_id']!=user_id].index,10)]
    y_valid = len(y_valid_rand_fakes.index)*[False]
    X_valid = visual_f.loc[y_valid_rand_fakes.index]
    score = clf.score(X_valid,y_valid)
    # print(score)
    scores_sum += score
    run_count += 1
    # print(scores_sum/run_count)
print(scores_sum/run_count)

  0%|                                                                                          | 0/300 [00:00<?, ?it/s]
  0%|2                                                                                 | 1/300 [00:04<21:54,  4.40s/it]
  1%|5                                                                                 | 2/300 [00:08<21:31,  4.33s/it]
  1%|8                                                                                 | 3/300 [00:13<21:37,  4.37s/it]
  1%|#                                                                                 | 4/300 [00:17<21:40,  4.39s/it]
  2%|#3                                                                                | 5/300 [00:21<21:15,  4.32s/it]
  2%|#6                                                                                | 6/300 [00:25<21:10,  4.32s/it]
  2%|#9                                                                                | 7/300 [00:30<20:43,  4.24s/it]
  3%|##1                                                                               | 8/300 [00:34<20:55,  4.30s/it]
  3%|##4                                                                               | 9/300 [00:39<21:13,  4.38s/it]
  3%|##7                                                                              | 10/300 [00:43<20:57,  4.34s/it]
  4%|##9                                                                              | 11/300 [00:47<21:05,  4.38s/it]
  4%|###2                                                                             | 12/300 [00:52<20:55,  4.36s/it]
  4%|###5                                                                             | 13/300 [00:56<20:50,  4.36s/it]
  5%|###7                                                                             | 14/300 [01:00<20:45,  4.35s/it]
  5%|####                                                                             | 15/300 [01:04<20:25,  4.30s/it]
  5%|####3                                                                            | 16/300 [01:09<20:38,  4.36s/it]
  6%|####5                                                                            | 17/300 [01:13<20:36,  4.37s/it]
  6%|####8                                                                            | 18/300 [01:18<20:16,  4.31s/it]
  6%|#####1                                                                           | 19/300 [01:22<20:21,  4.35s/it]
  7%|#####4                                                                           | 20/300 [01:27<20:50,  4.47s/it]
  7%|#####6                                                                           | 21/300 [01:31<20:23,  4.39s/it]
  7%|#####9                                                                           | 22/300 [01:35<20:26,  4.41s/it]
  8%|######2                                                                          | 23/300 [01:40<20:14,  4.38s/it]
  8%|######4                                                                          | 24/300 [01:44<20:15,  4.40s/it]
  8%|######7                                                                          | 25/300 [01:48<20:05,  4.38s/it]
  9%|#######                                                                          | 26/300 [01:53<20:04,  4.40s/it]
  9%|#######2                                                                         | 27/300 [01:58<20:31,  4.51s/it]
  9%|#######5                                                                         | 28/300 [02:03<21:49,  4.81s/it]
 10%|#######8                                                                         | 29/300 [02:08<22:09,  4.90s/it]
 10%|########1                                                                        | 30/300 [02:13<21:27,  4.77s/it]
 10%|########3                                                                        | 31/300 [02:17<20:46,  4.63s/it]
 11%|########6                                                                        | 32/300 [02:22<20:41,  4.63s/it]
 11%|########9                                                                        | 33/300 [02:26<20:14,  4.55s/it]
 11%|#########1                                                                       | 34/300 [02:30<20:00,  4.51s/it]
 12%|#########4                                                                       | 35/300 [02:35<19:18,  4.37s/it]
 12%|#########7                                                                       | 36/300 [02:39<19:40,  4.47s/it]
 12%|#########9                                                                       | 37/300 [02:44<19:23,  4.42s/it]
 13%|##########2                                                                      | 38/300 [02:48<19:15,  4.41s/it]
 13%|##########5                                                                      | 39/300 [02:52<19:12,  4.42s/it]
 13%|##########8                                                                      | 40/300 [02:57<18:58,  4.38s/it]
 14%|###########                                                                      | 41/300 [03:01<18:52,  4.37s/it]
 14%|###########3                                                                     | 42/300 [03:05<18:39,  4.34s/it]
 14%|###########6                                                                     | 43/300 [03:10<18:36,  4.35s/it]
 15%|###########8                                                                     | 44/300 [03:14<18:22,  4.31s/it]
 15%|############1                                                                    | 45/300 [03:18<18:24,  4.33s/it]
 15%|############4                                                                    | 46/300 [03:23<18:29,  4.37s/it]
 16%|############6                                                                    | 47/300 [03:27<18:24,  4.37s/it]
 16%|############9                                                                    | 48/300 [03:31<18:17,  4.36s/it]
 16%|#############2                                                                   | 49/300 [03:36<18:04,  4.32s/it]
 17%|#############5                                                                   | 50/300 [03:40<17:50,  4.28s/it]
 17%|#############7                                                                   | 51/300 [03:44<17:45,  4.28s/it]

In [8]:
'''
y_valid_fakes = data_f_fake.loc[data_f_fake['user_id']==user_id]
y_valid = len(y_valid_fakes.index)*[False]
X_valid = visual_f.loc[y_valid_fakes.index]
'''

"\ny_valid_fakes = data_f_fake.loc[data_f_fake['user_id']==user_id]\ny_valid = len(y_valid_fakes.index)*[False]\nX_valid = visual_f.loc[y_valid_fakes.index]\n"

In [9]:
# y_valid

In [11]:
y_train.shape[0]

7200